AWSTemplateFormatVersion: '2010-09-09'
Description: Stack de CloudFormation para desplegar instancias Amazon Linux 2, Windows Server y Ubuntu con SSM Agent activo.

Parameters:
  KeyName:
    Description: Nombre de la llave SSH para acceso a las instancias
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Debe ser el nombre de una llave SSH existente.
  VpcId:
    Description: ID de la VPC donde se desplegar치n los recursos
    Type: 'AWS::EC2::VPC::Id'
    ConstraintDescription: Debe ser un ID de VPC v치lido.
  SubnetId:
    Description: ID de la subred donde se desplegar치n las instancias
    Type: 'AWS::EC2::Subnet::Id'
    ConstraintDescription: Debe ser un ID de subred v치lido en la VPC especificada.

Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Permitir acceso SSH y RDP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3389'
          ToPort: '3389'
          CidrIp: 0.0.0.0/0

  SSMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SSMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:DescribeInstanceInformation'
                  - 'ssm:GetCommandInvocation'
                  - 'ssm:ListInstanceAssociations'
                  - 'ssm:PutInventory'
                  - 'ssm:UpdateInstanceInformation'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ec2messages:AcknowledgeMessage'
                  - 'ec2messages:DeleteMessage'
                  - 'ec2messages:FailMessage'
                  - 'ec2messages:GetEndpoint'
                  - 'ec2messages:GetMessages'
                  - 'ec2messages:SendReply'
                Resource: '*'

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref SSMRole

  LinuxInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !GetAtt InstanceSecurityGroup.GroupId
      ImageId: 'ami-01b799c439fd5516a'  # Amazon Linux 2023
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y amazon-ssm-agent
          systemctl enable amazon-ssm-agent
          systemctl start amazon-ssm-agent
      Tags:
        - Key: Name
          Value: Seb-LinuxInstance

  WindowsInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !GetAtt InstanceSecurityGroup.GroupId
      ImageId: 'ami-04df9ee4d3dfde202'  # Windows Server 2022
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          Install-WindowsFeature -Name "Web-Server" -IncludeManagementTools
          Invoke-WebRequest https://s3.amazonaws.com/amazon-ssm-us-east-1/latest/windows_amd64/AmazonSSMAgentSetup.exe -OutFile $env:ProgramFiles\Amazon\SSMAgent\AmazonSSMAgentSetup.exe
          Start-Process -FilePath $env:ProgramFiles\Amazon\SSMAgent\AmazonSSMAgentSetup.exe -ArgumentList /S -Wait
          Set-Service -Name AmazonSSMAgent -StartupType Automatic
          Start-Service -Name AmazonSSMAgent
          </powershell>
      Tags:
        - Key: Name
          Value: Seb-WindowsInstance

  UbuntuInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !GetAtt InstanceSecurityGroup.GroupId
      ImageId: 'ami-04b70fa74e45c3917'  # Ubuntu 24.04 LTS
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          snap install amazon-ssm-agent --classic
          systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
          systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service
      Tags:
        - Key: Name
          Value: Seb-UbuntuInstance